### PR TITLE
fix(language-core): re-parse template when interpolation syntax breaks

### LINKED ISSUE #5964: Mistaken syntax parsing for double curly braces of vue template
### Vue - Official extension or vue-tsc version

3.2.4

### VSCode version

1.109.3  b6a47e94e326b5c209d118cf0f994d6065585705  x64

### Vue version

3.5.27

### TypeScript version

5.9.3

### System Info

```shell
System:
    OS: Windows 11 10.0.26200
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 7.83 GB / 15.73 GB
  Binaries:
    Node: 22.17.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Users\A1777\AppData\Roaming\npm\yarn.CMD
    npm: 10.9.2 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 145.0.7632.75
    Edge: Chromium (140.0.3485.54)
```

### package.json dependencies

```json
{
  "dependencies": {
    "pinia": "^3.0.4",
    "vue": "^3.5.24"
  },
  "devDependencies": {
    "@types/node": "^24.10.1",
    "@vitejs/plugin-vue": "^6.0.1",
    "@vue/tsconfig": "^0.8.1",
    "typescript": "~5.9.3",
    "vite": "^7.2.4",
    "vue-tsc": "^3.1.4"
  }
}
```

### Steps to reproduce

Damage one of two double curly braces at the end closer to the other, and then repair it.

https://github.com/user-attachments/assets/06417156-6d51-4859-820b-9d2423b81d8e

### What is expected?

The two objects that were parsed as one single object after the damage should revert to their original state.

### What is actually happening?

It is necessary to delete one of the objects and add it back for proper parsing to occur. 

Image

### Link to minimal reproduction

_No response_

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by Dsaquel**
close #5964

preview:
Peek 2026-02-19 00-01

### CODE REVIEW

File: packages/language-core/lib/plugins/vue-template-html.ts [hunk 1]
```diff
@@ -191,6 +191,9 @@ const plugin: VueLanguagePlugin = ({ modules }) => {
 							}
 							else {
 								node.content = node.loc.source;
+								if (node.content.includes('{{') || node.content.includes('}}')) {
+									return false;
+								}
```
Comment (KazariEX) [inline packages/language-core/lib/plugins/vue-template-html.ts]: I think it shoule be placed after L181.

File: packages/language-core/lib/plugins/vue-template-html.ts [hunk 2]
```diff
@@ -179,6 +179,9 @@ const plugin: VueLanguagePlugin = ({ modules }) => {
 						if (!tryUpdateNode(node.content)) {
 							return false;
 						}
+						if (node.content.loc.source.includes('{{') || node.content.loc.source.includes('}}')) {
```
Comment (KazariEX) [inline packages/language-core/lib/plugins/vue-template-html.ts]: Use `.content` instead of `.loc.source` to align with L166.
